### ISSUE TITLE
Timeline of next sphinx-needs release

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#1142]
Hi @danwos and @chrisjsewell, can you please give a short outlook on the next planned release date?

I'm eager to integrate some features which currently are on master into our project (see also: https://github.com/useblocks/sphinx-needs/pull/1104#issuecomment-1978845703 ).

**Comment by chrisjsewell** [comment]
Heya, yeh that's my bad; I've been ill for the last week, so haven't been able to push things forward as quickly.
Hopefully, nearly better now, so will give a timeline soon 🤞

**Comment by arwedus** [comment]
@chrisjsewell @danwos : Any timeline yet? I'm considering to fork sphinx-needs to create a "current main" version, I assume 2.1rc0 is safe?

**Comment by holmboe** [comment]
@arwedus it seems this issue could be closed as [2.1.0](https://github.com/useblocks/sphinx-needs/releases/tag/2.1.0) is released. This question should probably be a "[Discussion](https://github.com/useblocks/sphinx-needs/discussions)" rather than an "Issue". I don't intend to be nitpicky, just stumbled upon this and saw it was open so thought I'd drop in to clear things out.
