### ISSUE TITLE
problem with rendering `style: datatables` when max-width of a page is changed.

### ISSUE THREAD

**Issue by sembooooo** [useblocks/sphinx-needs#1174]
Hi , 
I am again back to sphinx needs from another company 😁.
Its been very long time @twodrops  and @danwos .How are you ?

I have modified the width of the page using the below
```css
.wy-nav-content {
    max-width: 900px 
}
```
The below is rendering as shown in the pic.
```rst

.. needtable::
   :style: datatables
   :status: open
```
![image](https://github.com/useblocks/sphinx-needs/assets/15256713/fa35c3d9-8a47-4853-b862-fe5ca38220af)

If I change the max-width to 1200 then its looks like below
![image](https://github.com/useblocks/sphinx-needs/assets/15256713/57ef0d5c-07d2-4fb1-a9a2-7179aceb861d)

Could you please help me by providing a resolution ? 
thank you very much.

**Comment by twodrops** [comment]
@sembooooo Nice to hear from you again and glad to see that you are still using sphinx-needs in your new job :)

The issue you mentioned is same as https://github.com/useblocks/sphinx-needs/issues/771.
The fix is still not part of RTD. Meanwhile we (in our project) moved away from RTD and did not follow this up. I somehow thought I haven't seen this issue anymore with the latest RTD versions as well. Maybe I am mistaken.

**Comment by sembooooo** [comment]
Thanks for the answer. 
I will close this for now and will reopen this if i have any other problems
