### ISSUE TITLE
Create filter for needs.json export 

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs#655]
Current needs builder exports the already imported needs.json (with needimport) when "needs" builder is used.

**Comment by danwos** [comment]
The user can already define their own export filter when using the `needs.json` builder:
https://sphinx-needs.readthedocs.io/en/latest/configuration.html#needs-builder-filter

Is this already enough or is the goal of this ticket to update the default filter, so that all imported needs do not get exported?

**Comment by twodrops** [comment]
@danwos Yes, the second part. The imported needs with `needimport` shall not be exported. I guess this can be done by using "tags" with `needimport` and a filter expression in `needs-builder-filter` using the tags right. If yes, this can be closed.

Thanks for the hint.

**Comment by danwos** [comment]
Feature is already available as described by @twodrops
