### ISSUE TITLE
poetry version not updated in pyproject.toml

### ISSUE THREAD

**Issue by arwedus** [useblocks/sphinx-needs#866]
The poetry version dependency seems to have been updated to v1.3, but the following line still refers to poetry-core 1.0.8:

https://github.com/useblocks/sphinx-needs/blob/74bcd4516ced0c04a326f2002e0cb3b75c1183da/pyproject.toml#L136

Anyhow, when trying to run `poetry install` on a fresh repo clone with `poetry=1.1.13`, I just get:

```
  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at /usr/local/lib/python3.8/dist-packages/poetry/packages/locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
```

**Comment by danwos** [comment]
Interesting, I haven't seen this error during my tests for #868.

However, there was/is another poetry problem with poetry-core 1.5.0, which introduces some additional checks for the configuration file, so some configs are not valid anymore.
We fixed this also with #868 and updated the poetry.lock file.

I hope this issue is also fixed with it. Will create a new release soon.
