### ISSUE TITLE
Using sphinx-needs as module in custom directives

### ISSUE THREAD

**Issue by kreuzberger** [useblocks/sphinx-needs#879]
Hi!

Not sure how to solve, so this issue is just more for discussion:

During generation of my documents i have VERY often the same code with less differences.

```
.. needtable:: <ALWAYS SAME_TITLE>
  :style> ALWAYSSAME
  :filter: <DIFFERENT BUT SIMPLE STRING>
  ```

This is to verbose cause e.g. if i want to change something i would have to search/replace many lines, code is bloatet.
Due to DOC-AS-CODE i need a function. Ok, this means - with my limited knowledge - i could write a custom directive,
give the filter as argument BUT then have to generate the table myself.

How could this easily be achieved?

1) Create custom directive and create the rst code inside the directive and let it get parsed? I do something similar in other directives with ` self.state.inline_text`. For example

```
.. alwayssametable:: id in ["TEST_"]
````
would create the rst text for the needtable like shown above.

2) Better use sphinx-needs code as "module"? `from sphinx_needs import ?` and use a "function" insinde the directive implementation to get  a table node? Like
```
node_table = needs.node_table(title="abc", filter="", style="")
```
3) Any other solution that is not part of my solution space? Any unknown rst techniques? Substitutions and includes do not properly work in this case i think. Preprocessing of the files is also not desirable but possible (e.g. to add the snippets by the preprocessing tool, in my case cmake).

Any help appreciated

**Comment by danwos** [comment]
I see two additional solutions, which are also working today:

1) jinja function
2) sphinx-needs post templates

### 1) Jinja functions
I don't have a ready-to-work config for you, but I did it several times in the past.
The idea is to let Jinja parse all your rst-files before the rst-data is handled by Sphinx.
So you get all the power of Sphinx and could register own functions in the Jinja Environment.

To activate Jinja usage, follow this great blog post from Eric Holscher: https://ericholscher.com/blog/2016/jul/25/integrating-jinja-rst-sphinx/

Then you could write a function and call it in each rst-file, where it is needed:
```python
def my_table(filter_string):
    table = f"""
    .. needtable:: My caption
       :style: table
       :filter: {{filter_string}}
    """
    return table

html_context = {  # Untested
    'my_table': my_table
}
# Or register the function directly in the Jinja ENV.
```


In rst:
```rst
{{ my_table('status == "open"') }}
```

### 2) sphinx-needs post templates
If your needtables shall be always below some specific needs, e.g. because you document ``Tools`` and each ``tool-need`` shall get a table of connected other tools, then you can use the post_templates of needs.

https://sphinx-needs.readthedocs.io/en/latest/directives/need.html#post-template

This also support jinja and you have access to the need-data, so that the filter-string can be dynamic:

```rst
# needs_templates/tools_post.need

.. needtable:: Analysis of {{ id }}: {{ title }}
   :style: data
   :filter_string: {{id}} in my_special_link
```

I hope these two solutions can already cover your use case. If not, I'm happy to discuss a cool, new feature :)

**Comment by kreuzberger** [comment]
Ok, thanks. The solution Number with `jinja` seems to fit best and due to the fact that it is sphinx internal preprocessing it is ok for me. Never did it before, but i will try it. THANKS for the support!
